apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2 
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: 382904467012.dkr.ecr.us-east-1.amazonaws.com/springboot-repo-mavenapp

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 

    