apiVersion: v1
kind: Service
metadata:
  name: maven-service  
  labels:
    app: spring-boot-k8s
spec:
  ports:
  - nodePort: 30500
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-k8s
  type: NodePort